---
- name: Add hosts to Citrix Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false
  
  tasks:

  - name: Setup server
    citrix.adc.citrix_adc_server:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      state: present
      name: "{{ inventory_hostname }}"
      ipaddress: "{{ ip_addr }}"
    delegate_to: localhost
  
  - name: Setup service group and add host
    citrix.adc.citrix_adc_servicegroup:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      servicegroupname: service-group-https
      maxclient: "4000"
      servicetype: SSL
      servicemembers:
        mode: bind
        attributes: 
          - servername: "{{ inventory_hostname }}"
            port: 443
            weight: "50"
      monitor_bindings:
        mode: exact
        attributes:
          - monitor_name: ping
            weight: "50"
          - monitor_name: https
            weight: "50"
    delegate_to: localhost

  ##- name: Setup ssl certificate key
  ##  citrix.adc.citrix_adc_ssl_certkey:
  ##    nsip: "{{ nsip }}"
  ##    nitro_user: "{{ nitro_user }}"
  ##    nitro_pass: "{{ nitro_pass }}"
  ##    certkey: ns-server-certificate
  ##    cert: shadowman_combined.cert
  ##    key: shadowman_private.key
  ##    expirymonitor: enabled
  ##    notificationperiod: 30
  ##    inform: PEM
  ##    password: False
  ##    passplain: "{{ nitro_pass }}"
  ##  delegate_to: localhost

  - name: Setup lb server
    citrix.adc.citrix_adc_lb_vserver:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      name: lb-vserver-https
      servicetype: TCP
      port: 443
      ipv46: 172.16.3.123
      servicegroupbindings:
        - servicegroupname: service-group-https
    delegate_to: localhost

  - name: Set stats for the e-mail body and ServiceNow
    set_stats:
      data:
        email_body: "{{ email_body }} Load Balancer: https://citrixlb.shadowman.dev"
        work_notes: "{{ work_notes }} [code]<a href='https://citrixlb.shadowman.dev'>Load Balancer</a>[/code]"
    run_once: true      
    when: email_body is defined