---
- name: Add hosts to F5 Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false

  tasks:

  - name: Setup provider
    set_fact:
     provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: "no"
  
  - name: Create Nodes
    bigip_node:
      provider: "{{ provider }}"
      host: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      monitors:
        - /Common/icmp
        - /Common/https_443
    delegate_to: localhost

  - name: Create Pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "https_pool"
      lb_method: "round-robin"
      monitors: 
        - "/Common/https_443"
      monitor_type: "and_list"
    delegate_to: localhost

  - name: Add Pool Members
    bigip_pool_member:
      provider: "{{ provider }}"
      state: "present"
      host: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      port: "443"
      pool: "https_pool"
    delegate_to: localhost

  - name: Add Virtual Server
    bigip_virtual_server:
      provider: "{{ provider }}"
      name: "webapp"
      destination: "172.16.3.121"
      port: "443"
      enabled_vlans: "all"
      all_profiles: ['oneconnect']
      pool: "https_pool"
      snat: "Automap"
    delegate_to: localhost

  - name: Save Running Config
    bigip_config:
      provider: "{{ provider }}"
      save: yes
    delegate_to: localhost