- name: Push base device config
  hosts: "{{ device_name | default('all')}}"
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios
    - arista.eos

  tasks:
  
  - name: Push base vyos config
    vyos.vyos.vyos_config:
      src: templates/vyos_template.j2
      save: yes
    when: ansible_network_os == 'vyos.vyos.vyos'

  - name: Push base ios config
    cisco.ios.ios_config:
      src: templates/ios_template.j2
      save_when: changed
    when: ansible_network_os == 'cisco.ios.ios'

  - name: Push base eos config
    arista.eos.eos_config:
      src: templates/eos_template.j2
      save_when: changed
    when: ansible_network_os == 'arista.eos.eos'