- name: Reboot Device
  hosts: "{{ device_name | default('all')}}"
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios

  tasks:
  
  - name: Reboot VYOS
    vyos_command:
      commands:
      - reboot now
    when: ansible_network_os == 'vyos.vyos.vyos'

  - name: Reboot ios
    cli_command:
      command: reload
      check_all: true
      prompt:
        - Save?
        - confirm
      answer:
        - y
        - y
    when: ansible_network_os == 'cisco.ios.ios'

  - name: reset the connection
    meta: reset_connection

  - name: Wait for the network device to reload
    wait_for_connection:
      delay: 10