---
- name: Disable hosts on F5 Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false

  vars:
    pool_name: https_pool
  
  tasks:

  - name: Setup provider
    set_fact:
     provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: "no"

  - name: Set facts if enabling appserver
    set_fact:
      pool_name: app_pool
    when: inventory_hostname is match("appserver.*")
  
  - name: Disable Pool Members
    bigip_pool_member:
      provider: "{{ provider }}"
      state: "forced_offline"
      host: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      port: "443"
      pool: "{{ pool_name }}"
    delegate_to: localhost