---
- name: Enable hosts on Citrix
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false
  serial: 1

  
  tasks:
  
  - name: Enable Server on LB
    citrix.adc.citrix_adc_server:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      disabled: no
      ipaddress: "{{ ip_addr }}"
      name: "{{ inventory_hostname }}"
    delegate_to: localhost