---
- name: Manage Interfaces
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios
    - arista.eos

  tasks:
    - name: Update interfaces on vyos
      vyos.vyos.vyos_interfaces:
        state: "{{ state }}"
        config:
        - name: "{{ interface_name_vyos }}"
          description: "{{ description | default(omit) }}"
          speed: "{{ speed | default(omit) }}"
          duplex: "{{ duplex | default(omit) }}"
      when: ansible_network_os == 'vyos.vyos.vyos'

    - name: Update interfaces on ios
      cisco.ios.ios_interfaces:
        state: "{{ state }}"
        config:
        - name: "{{ interface_name_ios }}"
          description: "{{ description | default(omit) }}"
          enabled: true
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Update interfaces on eos
      arista.eos.eos_interfaces:
        state: "{{ state }}"
        config:
        - name: "{{ interface_name_eos }}"
          description: "{{ description | default(omit) }}"
          enabled: true
      when: ansible_network_os == 'arista.eos.eos'