---
- name: Manage L3 Interfaces
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios
    - arista.eos

  tasks:
    - name: Update l3 interfaces on vyos
      vyos.vyos.vyos_l3_interfaces:
        state: "{{ state }}"
        config:
        - name: eth1
          ipv4:
          - address: "{{ ipaddr }}"
      when: ansible_network_os == 'vyos.vyos.vyos'

    - name: Update l3 interfaces on ios
      cisco.ios.ios_l3_interfaces:
        state: "{{ state }}"
        config:
        - name: GigabitEthernet2
          ipv4:
          - address: "{{ ipaddr }}"
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Update l3 interfaces on eos
      arista.eos.eos_l3_interfaces:
        state: "{{ state }}"
        config:
        - name: Ethernet2
          ipv4:
          - address: "{{ ipaddr }}"
      when: ansible_network_os == 'arista.eos.eos'