---
- name: Manage Link Layer Discovery Protocol
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios

  tasks:
    - name: Update LLDP on vyos
      vyos_lldp_global:
        state: "{{ state }}"
        config:
          legacy_protocols: "{{ protocol | default(omit) }}"
      when: ansible_network_os == 'vyos.vyos.vyos'

    - name: Update LLDP on ios
      ios_lldp_global:
        state: "{{ state }}"
        config:
          holdtime: "{{ holdtime }}"
          enabled: true
          timer: 10
      when: ansible_network_os == 'cisco.ios.ios'