---
- name: Push Base config using resource modules
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios
    - arista.eos

  tasks:
  
  - name: Configure vyos
    block:
      - name: Configure hostname on vyos
        vyos.vyos.vyos_system:
          host_name: "{{ inventory_hostname }}"

      - name: Push base l3 interfaces to vyos
        vyos.vyos.vyos_l3_interfaces:
          state: overridden
          config:
          - name: eth0
            ipv4:
            - address: dhcp
          - name: eth1
            ipv4:
            - address: "{{ gigabit1 }}/28"

      - name: Push base interfaces to vyos
        vyos.vyos.vyos_interfaces:
          state: overridden
          config:
          - name: eth0
            enabled: true
            speed: auto
            duplex: auto
            description: This is the base config configured by Ansible
          - name: eth1
            enabled: true
          - name: lo
            enabled: true

      - name: Push base firewall global attributes configuration to vyos
        vyos.vyos.vyos_firewall_global:
          config:
            validation: strict
            config_trap: true
            log_martians: true
            syn_cookies: true
            twa_hazards_protection: true
            ping:
              all: true
              broadcast: true
            state_policy:
            - connection_type: established
              action: accept
              log: true
            - connection_type: invalid
              action: reject
            route_redirects:
            - afi: ipv4
              ip_src_route: true
              icmp_redirects:
                send: true
                receive: false
            group:
              address_group:
              - name: SALES-HOSTS
                description: Sales office hosts address list
                members:
                - address: 192.0.2.1
                - address: 192.0.2.2
                - address: 192.0.2.3
              - name: ENG-HOSTS
                description: Sales office hosts address list
                members:
                - address: 192.0.3.1
                - address: 192.0.3.2
              network_group:
              - name: MGMT
                description: This group has the Management network addresses
                members:
                - address: 192.0.1.0/24
          state: replaced

      - name: Push base firewall rules to vyos
        vyos.vyos.vyos_firewall_rules:
          state: overridden
          config:
          - afi: ipv4
            rule_sets:
            - name: INBOUND
              description: IPv4 INBOUND rule set
              default_action: accept
              rules:
              - number: 101
                action: accept
                description: Rule 101 is configured by Ansible
                ipsec: match-ipsec
              - number: 102
                action: reject
                description: Rule 102 is configured by Ansible
                ipsec: match-ipsec
            - name: OUTBOUND
              description: IPv4 OUTBOUND rule set
              default_action: accept
              rules:
              - number: 201
                action: accept
                description: Rule 201 is configured by Ansible
                ipsec: match-ipsec
              - number: 202
                action: reject
                description: Rule 202 is configured by Ansible
                ipsec: match-ipsec
            - name: LOCAL
              description: IPv4 LOCAL rule set
              default_action: accept
              rules:
              - number: 301
                action: accept
                description: Rule 301 is configured by Ansible
                ipsec: match-ipsec
              - number: 302
                action: reject
                description: Rule 302 is configured by Ansible
                ipsec: match-ipsec

      - name: Push base firewall interfaces to vyos
        vyos.vyos.vyos_firewall_interfaces:
          state: overridden
          config:
          - access_rules:
            - afi: ipv4
              rules:
              - name: INBOUND
                direction: in
              - name: OUTBOUND
                direction: out
              - name: LOCAL
                direction: local
            name: eth1      
        

      - name: Push base lldp global to vyos
        vyos.vyos.vyos_lldp_global:
          state: replaced
          config:
            legacy_protocols: 
              - fdp
              - cdp

      - name: Push base ospfv2 routes attributes configuration to vyos
        vyos.vyos.vyos_ospfv2:
          config:
            log_adjacency_changes: detail
            max_metric:
              router_lsa:
                administrative: true
                on_shutdown: 10
                on_startup: 10
            default_information:
              originate:
                always: true
                metric: 10
                metric_type: 2
                route_map: ingress
            mpls_te:
              router_address: 192.0.22.22
            auto_cost:
              reference_bandwidth: 2
            neighbor:
            - neighbor_id: 192.0.11.12
              poll_interval: 10
              priority: 2
            redistribute:
            - route_type: bgp
              metric: 10
              metric_type: 2
            passive_interface:
            - eth1
            parameters:
              router_id: 192.0.1.1
              opaque_lsa: true
              rfc1583_compatibility: true
              abr_type: cisco
            areas:
            - area_id: '2'
              area_type:
                normal: true
              authentication: plaintext-password
              shortcut: enable
            - area_id: '4'
              area_type:
                stub:
                  default_cost: 20
              network:
              - address: 192.0.2.0/24
              - address: 192.0.12.0/24
              - address: 192.0.22.0/24
              - address: 192.0.32.0/24
              range:
              - address: 192.0.42.0/24
                cost: 10
          state: replaced

      - name: Push base ospfv3 routes attributes configuration to vyos
        vyos.vyos.vyos_ospfv3:
          config:
            redistribute:
            - route_type: bgp
            parameters:
              router_id: 192.0.2.10
            areas:
            - area_id: '2'
              export_list: export1
              import_list: import1
              range:
              - address: 2001:db10::/32
              - address: 2001:db30::/32
              - address: 2001:db50::/32
            - area_id: '4'
              range:
              - address: 2001:db60::/32
          state: replaced
    when: ansible_network_os == 'vyos.vyos.vyos'

  - name: Configure ios
    block:

      - name: Configure hostname on ios
        cisco.ios.ios_system:
          hostname: "{{ inventory_hostname }}"

      - name: Update l3 interfaces on ios
        cisco.ios.ios_l3_interfaces:
          state: overridden
          config:
          - name: GigabitEthernet1
            ipv4:
            - address: dhcp
          - name: GigabitEthernet2
            ipv4:
            - address: "{{ gigabit2 }}/28"

      - name: Update interfaces on ios
        cisco.ios.ios_interfaces:
          state: overridden
          config:
          - name: GigabitEthernet1
            description: "This is {{ configured_by }}"
            enabled: true
          - name: GigabitEthernet2
            description: "This is {{ configured_by }}"
            enabled: true

      - name: Update lldp global on ios
        cisco.ios.ios_lldp_global:
          state: replaced
          config:
            holdtime: 10
            enabled: true
            timer: 10

      - name: Update lacp interfaces on ios
        cisco.ios.ios_lacp_interfaces:
          config:
          - name: GigabitEthernet1
            port_priority: 10
          - name: GigabitEthernet2
            port_priority: 20
          state: overridden

      - name: Update lldp interfaces on ios
        cisco.ios.ios_lldp_interfaces:
          state: overridden
          config:
            - name: GigabitEthernet1
              transmit: false
            - name: GigabitEthernet2
              transmit: false

      - name: Set base static_routes on ios
        cisco.ios.ios_static_routes:
          config:
          - address_families:
            - afi: ipv4
              routes:
              - dest: 198.51.100.0/24
                next_hops:
                - forward_router_address: 198.51.101.1
                  name: merged_route_1
                  distance_metric: 110
                  tag: 40
                  multicast: true
                - forward_router_address: 198.51.101.2
                  name: merged_route_2
                  distance_metric: 30
                - forward_router_address: 198.51.101.3
                  name: merged_route_3
          state: overridden

    when: ansible_network_os == 'cisco.ios.ios'

  - name: Configure eos
    block:
      - name: Configure hostname on eos
        arista.eos.eos_system:
          hostname: "{{ inventory_hostname }}"

      - name: Configure VLAN on eos
        arista.eos.eos_vlans:
          state: overridden
          config:
            - name: Desktop
              vlan_id: 20
              state: active
            - name: Server
              vlan_id: 30
              state: active
    
      - name: Update l3 interfaces on eos
        arista.eos.eos_l3_interfaces:
          state: overridden
          config:
          - name: Ethernet1
            ipv4:
            - address: "{{ gigabit1 }}/28"
          - name: Ethernet2
            ipv4:
            - address: "{{ gigabit2 }}/28"

      - name: Update l2 interfaces on eos
        arista.eos.eos_l2_interfaces:
          state: overridden
          config:
          - name: Ethernet1
            trunk:
              native_vlan: 20
          - name: Ethernet2
            access:
              vlan: 30

      - name: Update interfaces on eos
        arista.eos.eos_interfaces:
          state: overridden
          config:
          - name: Ethernet1
            description: "This is {{ configured_by }}"
            enabled: true
          - name: Ethernet2
            description: "This is {{ configured_by }}"
            enabled: true

    when: ansible_network_os == 'arista.eos.eos'
        