---
- name: Push Base config using resource modules
  hosts: all
  gather_facts: false
  collections:
    - vyos.vyos
    - cisco.ios

  tasks:

  - name: Configure vyos
    block:
      - name: Configure hostname on vyos
        vyos_system:
          host_name: "{{ inventory_hostname }}"

      - name: Push min l3 interfaces to vyos
        vyos_l3_interfaces:
          state: overridden
          config:
          - name: eth0
            ipv4:
            - address: dhcp
          - name: eth1
            ipv4:
            - address: "{{ gigabit1 }}/28"

      - name: Push min interfaces to vyos
        vyos_interfaces:
          state: overridden
          config:
          - name: eth0
            enabled: true
          - name: eth1
            enabled: true
          - name: lo
            enabled: true

      - name: Delete firewall interfaces on vyos
        vyos_firewall_interfaces:
          state: deleted

      - name: Delete firewall rules on vyos
        vyos_firewall_rules:
          state: deleted

      - name: Delete firewall global attributes configuration on vyos
        vyos_firewall_global:
          config:
            config_trap: 
            log_martians:
            syn_cookies: 
            twa_hazards_protection: 
            ping:
            state_policy:
            route_redirects:
            group:
          state: deleted

      - name: Delete lldp global on vyos
        vyos_lldp_global:
          state: deleted

      - name: Delete ospfv2 routes attributes configuration on vyos
        vyos_ospfv2:
          state: deleted

      - name: Delete ospfv3 routes attributes configuration on vyos
        vyos_ospfv3:
          state: deleted
    when: ansible_network_os == 'vyos.vyos.vyos'

  - name: Configure ios
    block:

      - name: Configure hostname on ios
        ios_system:
          hostname: "{{ inventory_hostname }}"

      - name: Set min l3 interfaces on ios
        ios_l3_interfaces:
          state: overridden
          config:
          - name: GigabitEthernet1
            ipv4:
            - address: dhcp
          - name: GigabitEthernet2
            ipv4:
            - address: "{{ gigabit2 }}/28"

      - name: Set min interfaces on ios
        ios_interfaces:
          state: overridden
          config:
          - name: GigabitEthernet1
            enabled: true
          - name: GigabitEthernet2
            enabled: true

      - name: Delete all lldp global on ios
        ios_lldp_global:
          state: deleted

      - name: Delete all lacp interfaces on ios
        ios_lacp_interfaces:
          state: deleted

      - name: Delete all static_routes on ios
        ios_static_routes:
          state: deleted
        ignore_errors: true
    when: ansible_network_os == 'cisco.ios.ios'

  - name: Configure eos
    block:

      - name: Configure hostname on eos
        eos_system:
          hostname: "{{ inventory_hostname }}"

      - name: Set min l3 interfaces on eos
        eos_l3_interfaces:
          state: overridden
          config:
          - name: Ethernet1
            ipv4:
            - address: "{{ gigabit1 }}/28"
          - name: Ethernet2
            ipv4:
            - address: "{{ gigabit2 }}/28"

      - name: Set min interfaces on eos
        eos_interfaces:
          state: overridden
          config:
          - name: Ethernet1
            enabled: true
          - name: Ethernet2
            enabled: true

      - name: Delete l2 interfaces on eos
        eos_l2_interfaces:
          config:
          - name: Ethernet1
          state: deleted
        ignore_errors: true

      - name: Delete VLAN on eos
        eos_vlans:
          config:
          - vlan_id: 20
          - vlan_id: 30
          state: deleted
        ignore_errors: true

    when: ansible_network_os == 'arista.eos.eos'