---
- name: Update user password on CIsco
  hosts: all
  gather_facts: false
  collections:
    - cisco.ios

  tasks:
    - name: Update Cisco User Password
      cisco.ios.ios_user:
        name: "{{ user }}"
        configured_password: "{{ new_password }}"
        update_password: always
        state: present
      no_log: true