---
- name: Remove hosts from Citrix Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false

  tasks:

  - name: Remove host from load balancer service group
    citrix.adc.citrix_adc_servicegroup:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      servicegroupname: service-group-https
      maxclient: "4000"
      servicetype: SSL
      servicemembers:
        mode: unbind
        attributes: 
          - servername: "{{ inventory_hostname }}"
            port: 443
            weight: "50"
    delegate_to: localhost

  - name: Remove server
    citrix.adc.citrix_adc_server:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      state: absent
      name: "{{ inventory_hostname }}"
      ipaddress: "{{ ip_addr }}"
    delegate_to: localhost