---
- name: Remove virtual server from F5 Load Balancer
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Setup provider
    set_fact:
     provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: "no"

  - name: Delete Virtual Server
    bigip_virtual_server:
      provider: "{{ provider }}"
      name: "{{ virtual_server_name }}"
      state: absent

  - name: Delete Pool
    bigip_pool:
      provider: "{{ provider }}"
      name: "{{ pool_name }}"
      state: absent

  - name: Save Running Config
    bigip_config:
      provider: "{{ provider }}"
      save: yes