---
- name: Remove hosts from Citrix Load Balancer
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false

  tasks:

  - name: Remove host from load balancer
    citrix.adc.citrix_adc_servicegroup:
      nsip: "{{ nsip }}"
      nitro_user: "{{ nitro_user }}"
      nitro_pass: "{{ nitro_pass }}"
      servicegroupname: service-group-https
      maxclient: 4000
      servicemembers:
        mode: unbind
        attributes: 
          - servername: "{{ inventory_hostname }}"
            port: 443
            ip: "{{ ip_addr }}"
            weight: 50
    delegate_to: localhost