---

- name: Add in Citrix SDK
  ansible.builtin.command:
    cmd: git clone https://github.com/citrix/citrix-adc-ansible-modules.git /tmp/citrix
  
- name: Install SDK
  ansible.builtin.command:
    cmd: pip3 install /tmp/citrix/deps/nitro-python-1.0_kamet.tar.gz

- name: Remove host from load balancer service group
  citrix.adc.citrix_adc_servicegroup:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    servicegroupname: service-group-https
    maxclient: "4000"
    servicetype: TCP
    validate_certs: false
    servicemembers:
      mode: unbind
      attributes:
        - servername: "{{ inventory_hostname }}"
          port: 443
          weight: "50"
  delegate_to: localhost

- name: Remove server
  citrix.adc.citrix_adc_server:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    state: absent
    name: "{{ inventory_hostname }}"
    ipaddress: "{{ ip_addr }}"
    validate_certs: false
  delegate_to: localhost
