- name: Disable Server from LB
  citrix.adc.citrix_adc_server:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    disabled: yes
    ipaddress: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    validate_certs: no
  delegate_to: localhost