---
- name: Add in Citrix SDK
  ansible.builtin.command:
    cmd: git clone https://github.com/citrix/citrix-adc-ansible-modules.git /tmp/citrix
  delegate_to: localhost
  
- name: Install SDK
  ansible.builtin.command:
    cmd: pip3 install /tmp/citrix/deps/nitro-python-1.0_kamet.tar.gz
  delegate_to: localhost
  
- name: Disable Server from LB
  citrix.adc.citrix_adc_server:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    disabled: true
    ipaddress: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false
  delegate_to: localhost
