- name: Delete Virtual Server
  citrix.adc.citrix_adc_lb_vserver:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    name: lb-vserver-https
    state: absent
    validate_certs: no
  notify: IDM_update

- name: Delete Servicegroup
  citrix.adc.citrix_adc_servicegroup:
    nsip: "{{ nsip }}"
    nitro_user: "{{ nitro_user }}"
    nitro_pass: "{{ nitro_pass }}"
    servicegroupname: service-group-https
    state: absent
    validate_certs: no